[project]
name = "ai-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.8.1",
    "pandas>=2.3.3",
    "psycopg[binary]>=3.2.13",
    "sqlalchemy>=2.0.44",
]
